alert('Listo para pelear');
var numuno = parseInt(prompt('Escribe tu primer numero'));
var numdos = parseInt(prompt('Escribe tu segundo numero'));
var resultado1 = (numuno + numdos);
var resultado2 = (numuno - numdos);
var resultado3 = (numuno * numdos);
var resultado4 = (numuno / numdos);
alert('Los resultados son:');
alert('suma=' + resultado1);
alert('resta=' + resultado2);
alert('multiplicacion=' + resultado3);
alert('division=' + resultado4);